server:
  port: 8088

spring:
  application:
    name: notification-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:inkwell_notifications}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    database-changelog-table: notification_changelog
    database-changelog-lock-table: notification_changelog_lock

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:placeholder}
    password: ${MAIL_PASSWORD:placeholder}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
