server:
  port: 8084

internal:
  secret: ${INTERNAL_SECRET:change-me-in-env}

spring:
  application:
    name: comment-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:inkwell_comments}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    database-changelog-table: comment_changelog
    database-changelog-lock-table: comment_changelog_lock

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, prometheus
