services:
  mysql:
    image: mysql:8.0
    container_name: inkwell-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: inkwell-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: inkwell-redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file: ./api-gateway/.env
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
    depends_on:
      eureka-server:
        condition: service_healthy
      redis:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file: ./auth-service/.env
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBIT_HOST=rabbitmq
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  post-service:
    build: ./post-service
    container_name: post-service
    env_file: ./post-service/.env
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBIT_HOST=rabbitmq
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  comment-service:
    build: ./comment-service
    container_name: comment-service
    env_file: ./comment-service/.env
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBIT_HOST=rabbitmq
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  category-service:
    build: ./category-service
    container_name: category-service
    env_file: ./category-service/.env
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  media-service:
    build: ./media-service
    container_name: media-service
    env_file: ./media-service/.env
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  newsletter-service:
    build: ./newsletter-service
    container_name: newsletter-service
    env_file: ./newsletter-service/.env
    ports:
      - "8087:8087"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBIT_HOST=rabbitmq
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    container_name: notification-service
    env_file: ./notification-service/.env
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - RABBIT_HOST=rabbitmq
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  admin-server:
    build: ./admin-server
    container_name: admin-server
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  inkwell-web:
    build: ./inkwell-web
    container_name: inkwell-web
    ports:
      - "9000:9000"
    environment:
      - EUREKA_HOST=eureka-server
      - EUREKA_URL=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
