CREATE DATABASE IF NOT EXISTS inkwell_auth;
CREATE DATABASE IF NOT EXISTS inkwell_posts;
CREATE DATABASE IF NOT EXISTS inkwell_comments;
CREATE DATABASE IF NOT EXISTS inkwell_notifications;
CREATE DATABASE IF NOT EXISTS inkwell_admin;
CREATE DATABASE IF NOT EXISTS inkwell_newsletter;
