server:
  port: 8761                        # Eureka's standard port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false     # don't register itself
    fetch-registry: false           # don't fetch its own registry
  server:
    wait-time-in-ms-when-sync-empty: 0
